config/routes.rb
Rails.application.routes.draw do

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete 'destroy_all' => 'cart_items#destroy_all', on: :collection
    end
    resources :orders, only: [:new, :create, :index, :show] do
      post 'confirm' => 'orders#confirm', on: :collection
      get 'complete' => 'orders#complete', on: :collection
    end
    resources :customers, only: [:show, :edit, :update] do
      get 'unsubscribe' => 'customers#unsubscribe', on: :collection
      patch 'withdraw'  => 'customers#withdraw', on: :collection
    end
  end



 devise_for :admin, skip: [:passwords] ,controllers: {
  registrations: "admin/registrations",
  sessions: "admin/sessions"
}

  #root to: 'admin/homes#top'
  get '/admin' => 'admin/homes#top'

  namespace :admin do
    resources :items, except: :destroy
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :index, :update] do
      resources :order_details, only: [:update], on: :collection
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admins.rb
module Admins
  def self.table_name_prefix
    'admins_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
  
  def sum_of_price
    item.taxin_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  # def active_for_authentication?
    # super && (self.is_deleted == false)
  # end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  # 画像アップデート用のメソット
  attachment :image

   def taxin_price
     (price*1.1).round
   end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_deposit: 0, payment_confirmation: 1, production: 2, preparing_ship: 3, sent: 4 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  validates :price, presence: true
  validates :amount, presence: true
  validates :making_status, presence: true

  enum making_status: { not_startable: 0, waiting_production: 1, production: 2, complete_production: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def create
    @genre = Genre.new
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
    
  end

  def index
   @genres = Genre.all
   @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
    
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :description, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
    @order = Order.page(params[:page]).per(10)
  end

  def show
    @order= Order.find(params[:id])
    @order_detail= @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = 'You have updated order successfully.'
      redirect_to admin_order_path
    else
      render :show
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>君がッ、、泣くまで、、ジャンル編集を辞めないッ！！</h1>
        <%= form_with url: admin_genre_path(@genre), model: @genre, local: true do |f| %>
         <%= f.label :ジャンル名 %>
         <%= f.text_field :name, placeholder: "ジャンル名", class: "offset-1" %>
         <%= f.submit "変更を保存", class: "btn btn-success offset-1" %>
        <% end %>

    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
  <div class="row">
    
    <div class="col-2"></div>
    <div class="col-7">
      <h1>ジャンル追加</h1>
      <%=form_with model:@genre, url: admin_genres_path, local:true do |f| %>
        <h2>ジャンル名</h2>
        <%= f.text_field :name %>
        <%= f.submit '新規登録', class: "btn btn-success offset-1" %>
      <% end %>
      <table>
        <thead>
          <tr>
            <th>ジャンル名</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
         <% @genres.each do |genre| %>
         <tr>
           <td>
            <%= genre.name %>
           </td>
           <td>　　　
          <%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %>
         <% end %>
           </td>
         </tr>
        </tbody>
      </table>
    </div>
    <div class="col-3"></div>
  </div>

app/views/admin/items/edit.html.erb
<div class="container my-5">
  <div class="row mx-auto mb-4">
    <h4 class = "col-auto text-center" style = "background-color:lightgray">商品編集</h4>
  </div>
    <%= form_with url:admin_item_path, model: @item, local:true do |f| %>

      <table class = "table table-borderless">
        <tr class="row ml-5">
          <th class = "offset-md-1 col-2"><%= f.label :商品画像 %></th>
          <td class = "col-8"><%= f.attachment_field :image %></td>
        </tr>

        <tr class="row ml-5">
          <th class = "offset-md-1 col-2"><%= f.label :商品名 %></th>
          <td class = "col-8"><%= f.text_field :name, class:"col-6" %></td>
        </tr>

        <tr class="row ml-5">
          <th class = "offset-md-1 col-2"><%= f.label :商品説明 %></th>
          <td><%= f.text_area :description , :size=>"44x6" %></td>
        </tr>

        <tr class="row ml-5">
          <th class = "offset-md-1 col-2"><%= f.label :ジャンル %></th>
        　<td class = "col-8"><%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "-- 選択してください --" }, class:"col-6" %></td>
        </tr>

        <tr class="row ml-5">
          <th class = "offset-md-1 col-2"><%= f.label :税抜価格 %></th>
          <td class = "col-8"><%= f.text_field :price , class:"col-6"%>&emsp;円</td>
        </tr>

        <tr class="row ml-5">
          <th class = "offset-md-1 col-2"><%= f.label :販売ステータス %></th>
          <td>
            <%= f.radio_button :is_active, true %>
            <span style="font-size:20px"><%= f.label :販売中 %></span>
            &emsp;
            <%= f.radio_button :is_active, false %>
            <span style="font-size:20px"><%= f.label :販売停止中 %></span>
          </td>
        </tr>
      </table>
  <div class="container">
    <div class="row">
      <%= f.submit '変更を保存', class: "mx-auto btn btn-outline-success" %>
    </div>
  </div>
    <% end %>
    

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<%= link_to "新規商品登録", new_admin_item_path %>

<% @items.each do |item| %>
  <p>商品ID<%= item.id %></p>

  <p>商品名<%= link_to item.name, admin_item_path(item) %></p>

  <p>税別価格<%= item.price %>円</p>

  <p>ジャンル<%= item.genre.name %></p>

  <p>販売ステータス<% if item.is_active? %>
    <span>販売中</span>
  <% else %>
    <span>販売停止中</span>
  <% end %>
  </p>

 <% end %>

app/views/admin/items/new.html.erb
<div class="continer">
  <div class="row">
    <div class="col-4">
    </div>
    <div class="col-6">
          <h1>商品新規登録</h1>
          <%= form_with model: @item, url: admin_items_path, local:true do |f| %>
            <h4>画像</h4>
            <%= f.attachment_field :image %>
          
            <h4>商品名</h4>
            <%= f.text_field :name %>
          
            <h4>商品説明</h4>
            <%= f.text_area :description %>
          
            <h4>ジャンル</h4>
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank:"-- 選択してください --" %>
          
            <h4>税抜価格</h4>
            <%= f.text_field :price %>円
          
            <h4>販売ステータス</h4>
            <%= f.radio_button :is_active, :true %>
              <%= f.label :"販売中" %>
              <%= f.radio_button :is_active, :false %>
              <%= f.label :"販売停止中" %>
          
            <%= f.submit '新規登録' %>
          
          <% end %>
    </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container my-5">
  <div class="row mx-auto mb-4">
    <h4 class = "col-auto text-center" style = "background-color:lightgray">商品詳細</h4>
  </div>

  <div class="row">
    <div class="col-4">
    <%= attachment_image_tag @item, :image, format: "jpeg", fallback: "no_image.jpg", size: "350x300" %>
    </div>

    <div class="offset-md-1 col-4">
      <table class = "table table-borderless">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.description %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        <tr>
          <th>税込価格</br>
          (税抜価格)</th>
          <td class=""><%= @item.taxin_price %>円</td>
          <td>(<%= @item.price %>円)</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @item.is_active? %>
              <strong class="text-success">販売中</strong>
            <% else %>
              <strong class="text-danger">販売停止中</strong>
            <% end %>
          </td>
        </tr>
      </div>
      </table>
    <div class="row mt-5">
      <%= link_to "編集する", edit_admin_item_path(@item),class: "mx-auto btn btn-outline-dark" %>
    </div>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col">
      <h4 class = "col-3 text-center" style = "background-color:lightgray">注文履歴一覧</h4>
      <table class = "table table-hover">

        <thead class = "thead-light">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>

        <% @orders.each do |order| %>
        <tbody>
          <tr>
            <td><%= link_to order.created_at.strftime('%Y/%m/%d'), admin_order_path(order.id) %></td>
            <td><%= order.customer.full_name %></td>
            <td><%= order.order_details.sum(:amount) %></td>
            <td><%= order.order_status_i18n %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="col-3 mx-auto">
        <strong><%= paginate @order %></strong>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class='container px-5 px-sm-0'>

    <div class='row'>
      <div class='col-md-12 offset-md-1'>
        <h2>注文履歴詳細</h2>
        <!-- 購入者情報 -->
        <table class='table table-hover table-inverse'>
          <tr>
              <th>購入者</th>
              <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
          </tr>
          <tr>
              <th>注文日</th>
              <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
              <th>配送先</th>
              <td><%= @order.address %></td>
          </tr>
          <tr>
              <th>支払方法</th>
              <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
              <th>注文ステータス</th>
              <td>
                <%= form_with model: @order, url: admin_order_path, local:true do |f| %>
                  <%#= f.collection_select :status, @order, :status, :status_i18n %>
                  <%= f.collection_select(:order_status, Order.order_statuses_i18n, :first, :last, {selected: @order.order_status}, {class: "form-control"}) %>
                  <%= f.submit "更新", :class=>"btn btn-success"%>
                <% end %>
              </td>
          </tr>
        </table>

        <!-- 購入商品情報 -->
        <div class='row'>
          <div class='col-8'>
            <table class='table table-hover table-inverse'>
              <thead>
                <tr class="table-secondary">
                  <th>商品名</th>
                  <th>単価（税込）</th>
                  <th>数量</th>
                  <th>小計</th>
                  <th>製作ステータス</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @order_detail.each do |order_detail| %>
                  <tr>
                    <td><%= order_detail.item.name %></td>
                    <td><%= order_detail.item.taxin_price %>円</td>
                    <td><%= order_detail.amount %></td>
                    <td><%= order_detail.item.taxin_price * order_detail.amount%>円</td>
                    <td>
                      <%= form_with model: order_detail, url:admin_order_order_detail_path(order_detail.id),  local:true do |f| %>
                        <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
                    </td>
                    <td><%= f.submit "更新", :class=>"btn btn-success"%></td>
                      <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
            <div class="d-inline col-4">
              <label><strong>請求情報</strong></label>
              <table class="table table-bordered">
                <tr>
                  <th class="table-secondary">商品合計</th>
                  <td><%= @order.total_payment - @order.shopping_cost %>円</td>
                </tr>
                <tr>
                  <th class="table-secondary">配送料</th>
                  <td><%= @order.shopping_cost %>円</td>
                </tr>
                <tr>
                  <th class="table-secondary"><strong>請求額合計</strong></th>
                  <td><%= @order.total_payment %>円</td>
                </tr>
              </table>
            </div>
          </div>
       </div>
     </div>
</div>