config/routes.rb
Rails.application.routes.draw do

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete 'destroy_all' => 'cart_items#destroy_all', on: :collection
    end
    resources :orders, only: [:new, :create, :index, :show] do
      post 'confirm' => 'orders#confirm', on: :collection
      get 'complete' => 'orders#complete', on: :collection
    end
    resources :customers, only: [:show, :edit, :update] do
      get 'unsubscribe' => 'customers#unsubscribe', on: :collection
      patch 'withdraw'  => 'customers#withdraw', on: :collection
    end
  end



 devise_for :admin, skip: [:passwords] ,controllers: {
  registrations: "admin/registrations",
  sessions: "admin/sessions"
}

  #root to: 'admin/homes#top'
  get '/admin' => 'admin/homes#top'

  namespace :admin do
    resources :items, except: :destroy
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :index, :update] do
      resources :order_details, only: [:update], on: :collection
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admins.rb
module Admins
  def self.table_name_prefix
    'admins_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
  
  def sum_of_price
    item.taxin_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  # def active_for_authentication?
    # super && (self.is_deleted == false)
  # end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  # 画像アップデート用のメソット
  attachment :image

   def taxin_price
     (price*1.1).round
   end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_deposit: 0, payment_confirmation: 1, production: 2, preparing_ship: 3, sent: 4 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  validates :price, presence: true
  validates :amount, presence: true
  validates :making_status, presence: true

  enum making_status: { not_startable: 0, waiting_production: 1, production: 2, complete_production: 3 }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :description, :price, :is_active, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/jeneres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1>ジャンル一覧/追加</h1>
      <%=form_with model:@genre, url:'/admin/genres', local:true do |f| %>
        <h2>ジャンル名</h2>
        <%= f.text_field :name %>
        <%= f.submit '新規登録' %>
      
      <% end %>
      
      <table>
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
         <% @junres.each do |junre| %>
         <tr>
           <td>
            <%= junre.name %>
            
           </td>
           <td>
             <%= link_to "編集する", edit_admin_genre_path(genre.id) %>
             <% end %>
           </td>
         </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_slide_show.html.erb
<div class="slider">
  <div class="slider_item">
      <%= image_tag 'cake01' %>
      <%= image_tag 'cake02' %>
      <%= image_tag 'cake03' %>
  </div>
</div>

app/views/layouts/_slider.html.erb
<div class="previews">
  <div class="slider">
    
    <div class="slider_01">
      <%= image_tag 'cake01' %>
      <p class="main-visual-text">
        Nagano Cake
      </p><br>
      <p class="main-visual-text2">
        しあわせのおすそわけ
      </p>
    </div>
    
    <div class="slider_02">
      <%= image_tag 'cake02' %>
      <p class="main-visual-text">
        鳩が食べても大丈夫
      </p><br>
      <p class="main-visual-text2">
        公園の鳩にもわけてあげよう
      </p>
    </div>
    
    <div class="slider_03">  
      <%= image_tag 'cake03' %>
      <p class="main-visual-text">
        😭クリスマス終了セール😭
      </p>
    </div>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <img class="navbar-brand" src="/assets/logo.png" href="/" alt="Nagano Cake">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", customer_path(current_customer.id), class: "btn btn-outline-secondary btn-sm" %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>
              <li class="nav-item">
                <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary btn-sm" %>
              </li>
            <% elsif admin_signed_in? %>
              <li>
                <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>
              <li>
                <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>

              <li>
                <%= link_to "注文履歴一覧", admin_orders_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>
              <li>
                <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary btn-sm" %>
              </li>
            <% else %>
              <li>
                <%= link_to "About", about_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>
              <li>
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>
              <li>
                <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>
              <li>
                <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary btn-sm" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>
  
  <footer>
      <div class="container footer">
        <div class="row">
          <div class="mx-auto">
            <p>POWERD BY MOUNTAINS</p>
          </div>
        </div>
      </div>
  </footer>
  
  
</html>